### ISSUE TITLE
Can we use Vite + Vue3 + Typescript + Antd Vue together?

### ISSUE THREAD

**Issue by xiaocode** [openwebf/webf#199]
### Should this be an RFC?

- [X] This is not a substantial change

### Description

I try to use Vite + Vue3 + Typescript + Antd Vue in webf, but it do not work. It repeat load css forever.

**Comment by andycall** [comment]
1. We didn't provide ES6 Module support from now on, So Vite can't be used from now on.
2. Vue3 now works well except `<transition></transition>` component which depends on `window.getComputedStyle` API, which is not support in the latest version of WebF.
3. The JavaScript Engine that WebF use is QuickJS, and it support ES2022 standard. It's free to use TypeScript as well.
4. The Antd could not be works well from now on, because we didn't provide much more CSS features to drive antd.
