### ISSUE TITLE
Stuck when rendering large text

### ISSUE THREAD

**Issue by devjiangzhou** [openwebf/webf#232]
### Affected version

main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

The push animation is not smooth when opening a new  webf page
The content of the file is about 20,000 words
[归档.zip](https://github.com/openwebf/webf/files/10543317/default.zip)

### Code example

@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
          // Center is a layout widget. It takes a single child and positions it
          // in the middle of the parent.
          child: MaterialButton(
              child: Text(
                '点击跳转',
                style: TextStyle(color: Colors.black),
              ),
              onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => const Reader()),
                  );
              }),
        ));
  }
}

class Reader extends StatefulWidget {
  const Reader({Key? key}) : super(key: key);

  @override
  State<Reader> createState() => _ReaderState();
}

class _ReaderState extends State<Reader> {
  @override
  Widget build(BuildContext context) {
    final MediaQueryData queryData = MediaQuery.of(context);
    final Size viewportSize = queryData.size;

    return Scaffold(
        body: WebF(
          devToolsService: ChromeDevToolsService(),
          viewportWidth: viewportSize.width - queryData.padding.horizontal,
          viewportHeight: viewportSize.height - queryData.padding.vertical,
          bundle: WebFBundle.fromUrl('assets:assets/demo.html'),
        )
    );
  }
}

https://user-images.githubusercontent.com/1578465/215682203-7c2642f5-cc4a-44d9-8f48-05b0c484ea6b.MP4

### Expected results

The push animation is smooth 

### Actual results

The push animation is not smooth

**Comment by andycall** [comment]
The JavaScript and Dart are running in one thread. If the JavaScript takes too much time, it will block the Dart and the animation will get stuck. 
To avoid the push animation getting stuck when rendering large text or other tasks than make JavaScript busy, there are to solutions:

1. Use the native push instead of the Flutter push. The animations are running in the native view thread, so JavaScrip won't affect the animation.
2. Use multiple Flutter engines. Once you separate the JavaScript and the Flutter UI thread, it won't get stuck anymore.
